GET  http://localhost:5000/

###

POST http://localhost:5000/
content-type: application/json

{
    "payer": "Coors",
    "points": 500,
    "timeStamp": "2017-10-31T15:00:00Z"

}

###
Get http://localhost:5000/balance

###

POST http://localhost:5000/spend
content-type: application/json

{
    "points": 700
}

###

{
    "id": "6b478dd8-7a98-4882-b3a0-c33c8da23766",
    "payer": "Dannon",
    "pointsBalance": 1100,
    "pointsLog": [
      {
        "points": 300,
        "timeStamp": 1604138400
      },
      {
        "points": -200,
        "timeStamp": 1604156400
      },
      {
        "points": 1000,
        "timeStamp": 1604325600
      }
    ]
  },
  {
    "id": "b7135eea-28eb-4067-9745-6e5f0e6c54fc",
    "payer": "Unilever",
    "pointsBalance": 200,
    "pointsLog": [
      {
        "points": 200,
        "timeStamp": 1604142000
      }
    ]
  },
  {
    "id": "dcb23427-8343-420b-be03-185fca1ebd79",
    "payer": "Miller Coors",
    "pointsBalance": 10000,
    "pointsLog": [
      {
        "points": 10000,
        "timeStamp": 1604239200
      }
    ]
  }