GET  http://localhost:5000/points/

###

GET  http://localhost:5000/points/92d6b6ad-c6f2-4321-9ab6-dc2c6d92cd39

###

POST http://localhost:5000/points/
content-type: application/json

{
    "payer": "Dannon",
    "points": 1000

}


###
DELETE http://localhost:5000/points/92d6b6ad-c6f2-4321-9ab6-dc2c6d92cd39

###

PUT  http://localhost:5000/points/
Content-Type: application/json

{
    "id": "c5007f26-6f74-499b-8022-08beb7fd00be",
    "payer": "Coors",
    "points": 1100
}

###


###