GET  http://localhost:5000/points/

###

GET  http://localhost:5000/points/92d6b6ad-c6f2-4321-9ab6-dc2c6d92cd39

###

GET http://localhost:5000/points/balance

###

POST http://localhost:5000/points/
content-type: application/json

{
    "payer": "Dannon",
    "points": 300,
    "timeStamp": "2020-10-31T10:00:00Z"

}


###
DELETE http://localhost:5000/points/0a95a291-1b10-455c-8641-c2244a9ecd53

###

PUT  http://localhost:5000/points/
Content-Type: application/json

{
    "id": "861cdb60-8dff-47fd-b609-0c7ce8e308c6",
    "payer": "Dannon",
    "points": 1000
}

###

PUT http://localhost:5000/points/spend
Content-Type: application/json

{
    "points": 500
}

###